### ISSUE TITLE
Hangs in the loop for www.heise.de

### ISSUE THREAD

**Issue by KommX** [adamalton/chrome-https-finder#3]
Just go to www.heise.de
My screen gets flooded with the notifications that I have been switched to https and the site doesn't load. Seems like a loop or so.

**Comment by adamalton** [comment]
Yeah, are you using it from the Chrome Webstore, or have you installed manually from the latest source code?

I think I've fixed this in the code, but I haven't released it to the webstore yet.  I'll update it when I get a mo!

**Comment by KommX** [comment]
I used the version from the Webstore.
How do I install it from the source?

**Comment by adamalton** [comment]
I've now updated the extension in the webstore, so if you've already got it
install then just going to chrome://extensions and hitting the "Update
extensions now" button should give you the latest version.

Adam

**Comment by KommX** [comment]
I think it takes some time until the new version gets deployes through the webstore.
https://chrome.google.com/webstore/detail/https-finder/fmbbgedgoimcifgdghmifpnpcfaioena?hl=en-US still states Version 1.0 from April 12th.

**Comment by KommX** [comment]
This one is fixed for me now.
